services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: movies:1.0.0
        container_name: movies-app
        env_file: ".env"
        environment:
            - PYDEVD_DISABLE_FILE_VALIDATION=1
        restart: unless-stopped
        command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        ports:
            - "8000:8000"
            - "5678:5678"
        volumes:
            - ./app:/code/app
            - ./migrations:/code/migrations
            - ./.env:/code/.env
        depends_on:
            - db
        networks:
            - movies

    db:
        image: postgres:16.3
        container_name: movies-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: movies
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        expose:
            - 5433
        networks:
            - movies

networks:
    movies:
        driver: bridge

volumes:
    database:
