"""create table movies

Revision ID: 0435f849237c
Revises: 196536c896c6
Create Date: 2025-04-06 09:51:57.458348

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0435f849237c"
down_revision: Union[str, None] = "196536c896c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("poster", sa.String(length=255), nullable=False),
        sa.Column("category_uuid", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_uuid"],
            ["categories.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_movies_category_uuid"),
        "movies",
        ["category_uuid"],
        unique=False,
    )
    op.create_index(op.f("ix_movies_uuid"), "movies", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movies_uuid"), table_name="movies")
    op.drop_index(op.f("ix_movies_category_uuid"), table_name="movies")
    op.drop_table("movies")
    # ### end Alembic commands ###
