"""change column user_id to user_uuid

Revision ID: 04c9824c6e39
Revises: 1ede76deb9c4
Create Date: 2025-04-13 16:19:27.691471

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04c9824c6e39"
down_revision: Union[str, None] = "1ede76deb9c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ratings", sa.Column("user_uuid", sa.UUID(), nullable=False))
    op.drop_index("ix_ratings_user_id", table_name="ratings")
    op.create_index(
        op.f("ix_ratings_user_uuid"), "ratings", ["user_uuid"], unique=False
    )
    op.drop_constraint("ratings_user_id_fkey", "ratings", type_="foreignkey")
    op.create_foreign_key(None, "ratings", "users", ["user_uuid"], ["uuid"])
    op.drop_column("ratings", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ratings",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "ratings", type_="foreignkey")
    op.create_foreign_key(
        "ratings_user_id_fkey", "ratings", "users", ["user_id"], ["uuid"]
    )
    op.drop_index(op.f("ix_ratings_user_uuid"), table_name="ratings")
    op.create_index("ix_ratings_user_id", "ratings", ["user_id"], unique=False)
    op.drop_column("ratings", "user_uuid")
    # ### end Alembic commands ###
