"""create table category

Revision ID: 196536c896c6
Revises: f415e5b881f9
Create Date: 2025-04-06 08:31:54.211860

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "196536c896c6"
down_revision: Union[str, None] = "f415e5b881f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "category",
            sa.Enum(
                "ACTION", "TERROR", "MUSICAL", "COMEDY", name="categorytype"
            ),
            nullable=False,
        ),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_categories_uuid"), "categories", ["uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_uuid"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
