"""remove poster from movies

Revision ID: 1ede76deb9c4
Revises: eb8324d70d5c
Create Date: 2025-04-12 14:06:24.443918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ede76deb9c4"
down_revision: Union[str, None] = "eb8324d70d5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "poster")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column(
            "poster",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
