"""add slug

Revision ID: 35d58f0913dd
Revises: 03a0f93b62e0
Create Date: 2025-04-12 11:07:32.626774

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35d58f0913dd"
down_revision: Union[str, None] = "03a0f93b62e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("slug", sa.String(length=120), nullable=False)
    )
    op.create_unique_constraint(None, "categories", ["slug"])
    op.add_column(
        "movies", sa.Column("slug", sa.String(length=120), nullable=False)
    )
    op.create_unique_constraint(None, "movies", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movies", type_="unique")
    op.drop_column("movies", "slug")
    op.drop_constraint(None, "categories", type_="unique")
    op.drop_column("categories", "slug")
    # ### end Alembic commands ###
