"""create table rate

Revision ID: 8c65e9b3dc61
Revises: 0435f849237c
Create Date: 2025-04-06 10:30:19.568424

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c65e9b3dc61"
down_revision: Union[str, None] = "0435f849237c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ratings",
        sa.Column("movie_uuid", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_uuid"],
            ["movies.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_ratings_movie_uuid"), "ratings", ["movie_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_ratings_user_id"), "ratings", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_ratings_uuid"), "ratings", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ratings_uuid"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_user_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_movie_uuid"), table_name="ratings")
    op.drop_table("ratings")
    # ### end Alembic commands ###
