"""remove relationship with category movies

Revision ID: eb8324d70d5c
Revises: 35d58f0913dd
Create Date: 2025-04-12 11:56:36.212581

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb8324d70d5c"
down_revision: Union[str, None] = "35d58f0913dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_movies_movie_category_uuid", table_name="movies")
    op.drop_constraint(
        "movies_movie_category_uuid_fkey", "movies", type_="foreignkey"
    )
    op.drop_column("movies", "movie_category_uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column(
            "movie_category_uuid",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "movies_movie_category_uuid_fkey",
        "movies",
        "movie_categories",
        ["movie_category_uuid"],
        ["uuid"],
    )
    op.create_index(
        "ix_movies_movie_category_uuid",
        "movies",
        ["movie_category_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###
