"""add column user_uuid

Revision ID: fc5d804d9e1d
Revises: bf640f3f16c1
Create Date: 2025-04-13 16:27:21.370424

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc5d804d9e1d"
down_revision: Union[str, None] = "bf640f3f16c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ratings", sa.Column("user_uuid", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_ratings_user_uuid"), "ratings", ["user_uuid"], unique=False
    )
    op.create_foreign_key(
        "ix_ratings_user_uuid", "ratings", "users", ["user_uuid"], ["uuid"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ix_ratings_user_uuid", "ratings", type_="foreignkey")
    op.drop_index(op.f("ix_ratings_user_uuid"), table_name="ratings")
    op.drop_column("ratings", "user_uuid")
    # ### end Alembic commands ###
